name: Deploy to Heroku

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # 2. Debugging - Check environment variables for troubleshooting
      - name: Debugging - Check secrets & environment
        run: |
          echo "HEROKU_API_KEY=${{ secrets.HEROKU_API_KEY }}"
          echo "HEROKU_APP_NAME=${{ secrets.HEROKU_APP_NAME }}"

      # 3. Build, Push, and Release with Heroku Docker deploy
      - name: Build, Push and Release a Docker container to Heroku
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          dockerfile_directory: ./
          dockerfile_name: Dockerfile
          docker_options: "--no-cache"
          process_type: web

      # Optional: Open the application after a successful deployment
      - name: Open the deployed app
        run: |
          heroku open --app ${{ secrets.HEROKU_APP_NAME }}
